user1 = User.create!(name: "Name1", username: "name1", password: "password")
user2 = User.create!(name: "Name2", username: "name2", password: "password")
user3 = User.create(name: "Name3", username: "name3", password: "password")
user4 = User.create(name: "Name4", username: "name4", password: "password")
user5 = User.create(name: "Name5", username: "name5", password: "password")
user6 = User.create(name: "Name6", username: "name6", password: "password")

calendar1a = Calendar.create(name: "Cal1a", unique_name: "cal1a", description: "This is cal1a", user_id: 1)
calendar1b = Calendar.create(name: "Cal1b", unique_name: "cal1b", description: "This is cal1b", user_id: 1)
calendar1c = Calendar.create(name: "Cal1c", unique_name: "cal1c", description: "This is cal1c", user_id: 1)
calendar2 = Calendar.create(name: "Cal2", unique_name: "cal2", description: "This is cal2", user_id: 2)
calendar3 = Calendar.create(name: "Cal3", unique_name: "cal3", description: "This is cal3", user_id: 3)
calendar4 = Calendar.create(name: "Cal4", unique_name: "cal4", description: "This is cal4", user_id: 4)

event1 = Event.create(name: "Birthday1", start_time: DateTime.new(2018, 3, 26.5),end_time: DateTime.new(2018, 3, 26.75), calendar_id: 1)
event3 = Event.create(name: "Birthday3", start_time: DateTime.new(2018, 3, 23.45),end_time: DateTime.new(2018, 3, 20.5), calendar_id: 1)
event2 = Event.create(name: "Birthday2", start_time: DateTime.new(2018, 3, 25.25),end_time: DateTime.new(2018, 3, 23.25), calendar_id: 2)
event4 = Event.create(name: "Birthday4", start_time: DateTime.new(2018, 3, 25.25),end_time: DateTime.new(2018, 3, 21.3), calendar_id: 2)
